apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: read-secret-and-cm
spec:
  template:
    spec:
      containers:
        - image: ko.local/read-secret-and-cm:0.1
          volumeMounts:
            - name: secret-vol
              mountPath: /etc/secret
              readOnly: true
            - name: configmap-vol
              mountPath: /etc/config
      volumes:
        - name: secret-vol
          secret:
            secretName: secret-msg
        - name: configmap-vol
          configMap:
            name: configmap-msg
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: read-secret-and-cm-trigger
spec:
  broker: default
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: read-secret-and-cm
